spring.application.name=aether-backend

# Conexión a un archivo local. Se creará solo si no existe.
spring.datasource.url=jdbc:sqlite:aether.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Usuario y contraseña vacíos (SQLite no los usa por defecto)
spring.datasource.username=
spring.datasource.password=

# Configuración de Hibernate para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=Kraj8AxPPe5XdByv9wN4o4cwhW8ExUoxH3kGIG9oY3MobGgN7zbPmmG2aomaZ7RP6EH17Le6RdX6+k0DPxqbfQ==
app.jwt.expiration-minutes=60

# Aceptar entradas desde otros dispositivos
server.address=0.0.0.0